# Generated by Django 5.0.1 on 2026-01-14 21:30

from django.db import migrations


def populate_roles(apps, schema_editor):
    """
    Creates default roles in the system, including the 'agent' role
    required for user registration.
    """
    Role = apps.get_model('users', 'Role')

    roles_to_create = [
        {'name': 'admin', 'display_name': 'Administrator'},
        {'name': 'agent', 'display_name': 'Agent'},
    ]

    for role_data in roles_to_create:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={'display_name': role_data['display_name']}
        )


def unpopulate_roles(apps, schema_editor):
    """Removes the default roles created by this migration."""
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(name__in=['admin', 'agent']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),  # Make sure this matches the last migration file for the 'users' app
    ]

    operations = [
        migrations.RunPython(populate_roles, reverse_code=unpopulate_roles),
    ]
