# Generated by Django 6.0.1 on 2026-01-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_populate_roles'),
        ('users', '0003_remove_user_roles_user_role'),
    ]

    operations = [
    ]
