# Generated by Django 6.0.1 on 2026-01-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('detected_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'profiler_chat_sessions',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EXTRACTION', 'Extraction'), ('SYNTHESIS', 'Synthesis'), ('VALIDATOR', 'Validator'), ('RATING', 'Rating'), ('SUMMARY', 'Summary'), ('COMPARISON', 'Comparison')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiler_prompt_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profiler.chatsession')),
            ],
            options={
                'db_table': 'profiler_chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('chat', 'Chat'), ('pdf', 'PDF'), ('docx', 'DOCX')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='profiler.chatsession')),
            ],
            options={
                'db_table': 'profiler_generated_outputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilingInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_subject', models.CharField(max_length=255)),
                ('inferred_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('key_attributes', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('risks_or_gaps', models.JSONField(blank=True, default=list)),
                ('notable_observations', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.chatsession')),
            ],
            options={
                'db_table': 'profiler_profiling_inferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawUserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('json', 'JSON'), ('pdf', 'PDF'), ('docx', 'DOCX')], max_length=20)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='raw_uploads/')),
                ('user_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_inputs', to='profiler.chatsession')),
            ],
            options={
                'db_table': 'profiler_raw_user_inputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='profiler.chatsession')),
                ('source_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_versions', to='profiler.rawuserinput')),
            ],
            options={
                'db_table': 'profiler_normalized_contexts',
                'ordering': ['-created_at'],
            },
        ),
    ]
