# Generated by Django 6.0.1 on 2026-01-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilinginference',
            old_name='risks_of_gaps',
            new_name='risks_or_gaps',
        ),
    ]
