# Generated by Django 6.0.1 on 2026-01-16 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_rename_risks_of_gaps_profilinginference_risks_or_gaps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilinginference',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='profilinginference',
            name='skills',
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='inferred_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='key_attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='limitations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='notable_observations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='risks_or_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiler.chatsession'),
        ),
        migrations.AlterField(
            model_name='profilinginference',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
