# Generated by Django 6.0.1 on 2026-01-24 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0002_fix_uuid_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedoutput',
            name='raw_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generatedoutput',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
