# Generated by Django 6.0.1 on 2026-01-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_alter_generatedoutput_raw_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptversion',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
