# Generated by Django 6.0.1 on 2026-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0004_alter_promptversion_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedoutput',
            name='structured_content',
            field=models.JSONField(blank=True, help_text="Flattened JSON containing 'observations', 'avg_confidence', and 'summary'.", null=True),
        ),
    ]
